In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print("type: %s" %type(a))
print("shape: %s" %a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

type: <class 'numpy.ndarray'>
shape: 3
1 2 3
[5 2 3]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print("shape of b:",b.shape) 
print(b[0,0],b[0,1],b[1,0])

shape of b: (2, 3)
1 2 4


In [5]:
a=np.zeros((2,2)) 
print("All zeros matrix: %s" %a)

All zeros matrix: [[0. 0.]
 [0. 0.]]


In [6]:
b=np.ones((1,2)) 
print("All ones matrix: %s" %a)

All ones matrix: [[0. 0.]
 [0. 0.]]


In [7]:
d=np.eye(2) 
print("identify matrix: %s" %d)

identify matrix: [[1. 0.]
 [0. 1.]]


In [8]:
e=np.random.random((2,2)) 
print("Random matrix: %s" %e)

Random matrix: [[0.77336852 0.14869934]
 [0.38121503 0.6717644 ]]


In [9]:
print("Vectorized sum example")
x=np.array([[1,2],[3,4]])
print("x: %s" %x)
print("Sum : %s"%np.sum(x))
print("sum axis=0 %s" %np.sum(x, axis=0))
print("sum axis=1 %s" %np.sum(x, axis=1))

Vectorized sum example
x: [[1 2]
 [3 4]]
Sum : 10
sum axis=0 [4 6]
sum axis=1 [3 7]


In [10]:
a=np.arange(10000)
b=np.arange(10000)
dp=np.dot(a,b)
print("Dot product :%s" %dp)

Dot product :-1724114088


In [13]:
op=np.outer(a,b)
print("Outer Product : %s" %op)
ep=np.multiply(a,b)
print("\n Element wise product:%s \n"%ep)

Outer Product : [[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]

 Element wise product:[       0        1        4 ... 99940009 99960004 99980001] 



In [12]:
x = np.array([[1,2], [3,4]])
print("Original X: %s" %x)
print("Transpose of x: %s" %x.T)


Original X: [[1 2]
 [3 4]]
Transpose of x: [[1 3]
 [2 4]]


In [14]:
from numpy import array
from scipy.linalg import svd
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
U, s, VT = svd(A)
print("U: %s" %U)
print("s: %s" %s)
print("VT: %s" %VT)

[[1 2]
 [3 4]
 [5 6]]
U: [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
s: [9.52551809 0.51430058]
VT: [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [ ]:
0